# Generated by Django 4.1.5 on 2023-01-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0002_admin_kitob_talaba_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitob',
            name='janr',
            field=models.CharField(choices=[('Badiiy', 'Badiiy'), ('Ilmiy', 'Ilmiy'), ('Hujjatli', 'Hujjatli'), ('Roman', 'Roman')], max_length=30),
        ),
    ]
