# Generated by Django 4.1.5 on 2023-01-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0003_alter_kitob_janr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitob',
            name='janr',
            field=models.CharField(choices=[('Badiiy', 'Badiiy'), ('Ilmiy', 'Ilmiy'), ('Hujjatli', 'Hujjatli')], max_length=30),
        ),
        migrations.AlterField(
            model_name='record',
            name='qatargan_sana',
            field=models.DateField(blank=True, null=True),
        ),
    ]
