# Generated by Django 4.1.5 on 2023-01-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0004_alter_kitob_janr_alter_record_qatargan_sana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talaba',
            name='bitiruvchi',
            field=models.BooleanField(default=False),
        ),
    ]
