# Generated by Django 4.1.5 on 2023-01-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0006_alter_muallif_tirik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='qatargan_sana',
        ),
        migrations.AddField(
            model_name='record',
            name='qaytargan_sana',
            field=models.DateField(blank=True, null=True),
        ),
    ]
